### ISSUE TITLE
No support for REST API

### ISSUE THREAD

**Issue by djmitche** [signalfx/signalfx-nodejs#19]
The Python client nicely supports the SignalFX REST API, but the node client appears not to.

**Comment by mpetazzoni** [comment]
That's correct. We're still working on bringing the various client libraries to feature parity!

/cc @molner @charliesignalfx

**Comment by jessdelacruzsantos** [comment]
Echo: It would be great to have this client interact with the SignalFx API

**Comment by jtmal-signalfx** [comment]
Hey everybody, please add a comment if you're still interested, and I'll add it to the backlog.

**Comment by jtmal-signalfx** [comment]
If anyone is still interested please add a comment and we'll reopen and look into it.
