### ISSUE TITLE
How do we use backfill api in this sdk?

### ISSUE THREAD

**Issue by brsanthu** [signalfx/signalfx-nodejs#36]
Title says it all. How do we use backfill api in this sdk?

**Comment by mpetazzoni** [comment]
@brsanthu, unfortunately the backfill API client is not implemented yet in the Node.js / Javascript SDK for SignalFx.

In the meantime, you can find the backfill API documentation at https://developers.signalfx.com/v2/reference#backfill.

Don't hesitate to get in touch with our Support team (support@signalfx.com) if you need help getting that going!
