### ISSUE TITLE
warning signalfx > text-encoding@0.6.4: no longer maintained

### ISSUE THREAD

**Issue by lennyburdette** [signalfx/signalfx-nodejs#46]
The text-encoding dependency is no longer maintained. According to [this comment](https://github.com/sinonjs/nise/issues/66#issuecomment-450403297) it was a polyfill for an API that's available in nodejs >= 8. 

Looks like Sinon first tried to vendor in the polyfill (https://github.com/sinonjs/nise/pull/80) but ended up creating their own fork instead: https://github.com/sinonjs/text-encoding

Happy to do the work if you can give me some guidance on your preferred direction. 😄

**Comment by mpetazzoni** [comment]
@lennyburdette thanks for the note. If I'm understanding this right by restricting ourselves to Node.js v8+ we wouldn't need the polyfill at all, correct? Otherwise, we'd need to switch to Sinon's version of the polyfill implementation?

**Comment by lennyburdette** [comment]
That’s my impression but I can’t say for sure

**Comment by mpetazzoni** [comment]
@kchengsf @cory-signalfx Any recommendations here? I'd be in favor of going with the times, but we might still need the polyfill to maintain in-browser support.

**Comment by lennyburdette** [comment]
This library currently supports node 4, so dropping support would require a major version bump at minimum.

**Comment by jtmal-signalfx** [comment]
I'll take a look, but this isn't high-priority so it might take a couple of days.

**Comment by jtmal-signalfx** [comment]
We've updated a lot of dependencies in 8.x so this doesn't apply anymore.
