### ISSUE TITLE
Cannot install due to node engine restriction in package.json

### ISSUE THREAD

**Issue by epechuzal** [signalfx/signalfx-nodejs#67]
I have been using this module for a while on v7.2.0, but lately my `yarn install` calls fail with this error
```
error signalfx@7.3.1: The engine "node" is incompatible with this module. Expected version ">=8.0.0 <11". Got "14.17.0"
```

I am guessing that a more recent release has changed the `engines.node` field to have a max value of 11, but node v8 and v10 are both already EOL and v16 is about to enter LTS.

I would advise updating the required node version to be `>= 8.0.0` with no max version, or set it to `>=8.0.0 <17`.

**Comment by jtmal-signalfx** [comment]
I've released a fix earlier today, which allows `>=8.0.0 <15`. Once `16` enters LTS, we'll adjust to `17`. In case I forget it, please go ahead and reopen.

**Comment by jtmal-signalfx** [comment]
I'll update in the PR for #70.

**Comment by jtmal-signalfx** [comment]
Forgot to close, latest version works in all LTSes.
